### ISSUE TITLE
Вёрстка главной страницы: мини-лендинг с презентацией игры.

### ISSUE THREAD

**Issue by vaskes79** [Shadow-Shamans/first-race#2]
Вёрстка главной страницы: мини-лендинг с презентацией игры.

Блок с игрой, кнопочки (регистрация, лидерборд), меню

**Comment by stevenKirill** [comment]
Эта страница будет на вместо экрана начать игру ? Я думаю нам надо типо меню сделать в игре с пунктом правила игры и там эта страница, почему именно лендинг ?

**Comment by Nintendodias** [comment]
А где было сказано про мини-лендинг для презентации? Я что-то не встречала такое...Или ты про демо?
