### ISSUE TITLE
Правки по дизайну от команды

### ISSUE THREAD

**Issue by toropanov** [Shadow-Shamans/first-race#39]
- [x] Уменьшить UI на игровом экране
- [x] Отрисовать кнопку Play и Pause
- [x] Уменьшить сетку тайлов до 128 x 128
- [x] В магазине не хватает выбора между вагонами и локомотивами
- [x] Выбор шахты (?)
- [x] Станции (Было опционально, думаю делать не нужно, чтобы не усложнять, пусть стартуем из отрисованных элементов старта)
- [x] Различные детальки, что бы карта была не просто травой с ячейками, а на ней какие нибудь детали были*

**Comment by dahah-babah** [comment]
https://github.com/Shadow-Shamans/first-race/issues/39
